Controllers/GameController.cs
using GameTrack.Data;
using GameTrack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GameTrack.Controllers
{
  public class GameController : Controller
  {
    private readonly ApplicationDbContext _context;

    public GameController(ApplicationDbContext context)
    {
      _context = context;
    }

    private bool GameExists(int id)
    {
      return _context.Games.Any(e => e.Id == id);
    }

    private async Task SetGenresAsync()
    {
      // Get all games
      var games = await _context.Games
       .Include(g => g.GenreNavigation)
       .ToListAsync();

      // Set the GenreNavigation property for each game
      foreach (var game in games)
      {
        game.GenreNavigation = await _context.Genres.FirstOrDefaultAsync(g => g.GenreId == game.Genre);
      }
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
      // Store all genres in ViewBag
      ViewBag.Genres = await _context.Genres.ToListAsync();
      await SetGenresAsync();

      return View(await _context.Games.ToListAsync());
    }

    [HttpGet]
    public IActionResult Create()
    {
      ViewBag.Categories = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Game game, IFormFile imageFile)
    {
      var allowenExtensions = new[] { ".jpg", ".png", ".jpeg" };

      if (imageFile != null)
      {
        // Check if the file is an image
        var extension = Path.GetExtension(imageFile.FileName).ToLowerInvariant();
        if (!allowenExtensions.Contains(extension))
        {
          ModelState.AddModelError("", "Only .jpg, .png, .jpeg files are allowed!");
        }
        else
        {
          // Check if the file size is less than 100MB
          if (imageFile.Length > 100 * 1024 * 1024)
          {
            ModelState.AddModelError("", "File size must be less than 100MB!");
          }
          // Generate a random file name
          var randomFileName = string.Format($"{Guid.NewGuid().ToString()}{extension}");
          var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", randomFileName);
          try
          {
            using (var stream = new FileStream(path, FileMode.Create))
            {
              await imageFile.CopyToAsync(stream);
            }
            Console.WriteLine("Image uploaded successfully!");
            game.Image = randomFileName;
            Console.WriteLine(game.Image);
          }
          catch
          {
            ModelState.AddModelError("", "There was an error while uploading the image!");
          }
        }
      }
      if (ModelState.IsValid)
      {
        // Add the game to the database
        _context.Add(game);
        game.GenreNavigation = await _context.Genres.FirstOrDefaultAsync(g => g.GenreId == game.Genre);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      else
      {
        foreach (var modelState in ModelState.Values)
        {
          foreach (var error in modelState.Errors)
          {
            Console.WriteLine(error.ErrorMessage);
          }
        }
        ViewBag.Categories = new SelectList(_context.Genres.ToList(), "GenreId", "Name");
        return View(game);
      }
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var game = await _context.Games.FindAsync(id);
      if (game == null)
      {
        return NotFound();
      }
      ViewBag.Categories = new SelectList(_context.Genres.ToList(), "GenreId", "Name", game.Genre);
      return View(game);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Game game, IFormFile imageFile)
    {
      if (id != game.Id)
      {
        return NotFound();
      }
      // Get the existing game
      var existingGame = await _context.Games.AsNoTracking().FirstOrDefaultAsync(g => g.Id == id);
      if (existingGame == null)
      {
        return NotFound();
      }

      ModelState.Remove("imageFile");

      var allowedExtensions = new[] { ".jpg", ".png", ".jpeg" };
      // Check if the image file is null or empty
      if (imageFile == null || imageFile.Length == 0)
      {
        game.Image = existingGame.Image;
      }
      else
      {
        // Check if the file is an image
        var extension = Path.GetExtension(imageFile.FileName).ToLowerInvariant();
        if (!allowedExtensions.Contains(extension))
        {
          ModelState.AddModelError("", "Only .jpg, .png, .jpeg files are allowed!");
        }
        else
        {
          if (imageFile.Length > 100 * 1024 * 1024)
          {
            ModelState.AddModelError("", "File size must be less than 100MB!");
          }
          // Generate a random file name
          var randomFileName = $"{Guid.NewGuid()}{extension}";
          var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", randomFileName);
          try
          {
            using (var stream = new FileStream(path, FileMode.Create))
            {
              await imageFile.CopyToAsync(stream);
            }
            game.Image = randomFileName;
          }
          catch
          {
            ModelState.AddModelError("", "There was an error while uploading the image!");
          }
        }
      }
      if (ModelState.IsValid)
      {
        _context.Update(game);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      else
      {
        foreach (var modelState in ModelState.Values)
        {
          foreach (var error in modelState.Errors)
          {
            Console.WriteLine(error.ErrorMessage);
          }
        }
        ViewBag.Categories = new SelectList(_context.Genres.ToList(), "GenreId", "Name", game.Genre);
        return View(game);
      }
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var game = await _context.Games.FirstOrDefaultAsync(m => m.Id == id);
      if (game == null)
      {
        return NotFound();
      }

      await SetGenresAsync();

      return View(game);
    }

    // POST: GameController/Delete/id
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var game = await _context.Games.FindAsync(id);

      var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", game.Image);

      try
      {
        System.IO.File.Delete(path);
      }
      catch
      {
        Console.WriteLine("There was an error while deleting the image!");
      }

      _context.Games.Remove(game);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }
  }
}

Controllers/GenreController.cs
using GameTrack.Data;
using GameTrack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GameTrack.Controllers
{
  public class GenreController : Controller
  {
    protected readonly ApplicationDbContext _context;

    public GenreController(ApplicationDbContext context)
    {
      _context = context;
    }

    // Check if a genre exists
    private bool GenreExists(int id)
    {
      return _context.Genres.Any(e => e.GenreId == id);
    }

    [HttpGet]
    public IActionResult Index()
    {
      var genres = _context.Genres.ToList();
      return View(genres);
    }

    [HttpGet]
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Genre genre)
    {
      if (ModelState.IsValid)
      {
        // Add the genre to the database if model is valid
        _context.Add(genre);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
      }
      return View(genre);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var genre = await _context.Genres.FindAsync(id);
      if (genre == null)
      {
        return NotFound();
      }

      return View(genre);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Genre genre)
    {
      if (id != genre.GenreId)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(genre);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!GenreExists(genre.GenreId))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }

      return View(genre);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var genre = await _context.Genres.FirstOrDefaultAsync(m => m.GenreId == id);
      if (genre == null)
      {
        return NotFound();
      }

      return View(genre);
    }

    // POST: Genres/Delete/id
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      // Delete the genre
      var genre = await _context.Genres.FindAsync(id);
      if (genre != null)
      {
        _context.Genres.Remove(genre);
        await _context.SaveChangesAsync();
      }

      return RedirectToAction(nameof(Index));
    }
  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameTrack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameTrack.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <style>
        .navbar-custom {
            background-color: #333; 
        }
        .navbar-custom .navbar-brand, 
        .navbar-custom .nav-link {
            color: #fff; 
        }
        .navbar-custom .nav-link:hover {
            color: #d4d4d4; 
        }
        .footer-custom {
            background-color: #333;
            color: #fff; 
            position: absolute;
            bottom: 0;
            width: 100%;
        }
        html, body {
            height: 100%;
            background-color: #f8f9fa; 
            font-family: 'Inter', sans-serif;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        .content-wrapper {
            flex: 1;
        }
    </style>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-custom navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container-fluid mx-5">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/img/GameTrackLogo.png" alt="GameTrack Logo" style="width: 75px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                    </li>
                </ul>
                <div class="d-flex align-items-center">
                    <button class="btn modern-btn me-2">Create Account</button>
                    <button class="btn modern-btn-outline">Log in</button>
                </div>
            </div>
        </div>
    </nav>
</header>

    <div class="content-wrapper">
        <main role="main" class="container pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>